saltstack-formulas/nagios-formula

README.rst
nagios/map.jinja
nagios/nrpe/dynamic.sls
nagios/nrpe/files/nrpe.cfg.jinja
nagios/nrpe/plugin.sls
nagios/nrpe/server.sls
nagios/server/dynamic.sls
pillar.example

This is the first of two forthcoming PRs relating to dynamic Nagios configuration using Salt.
This PR adds the capability to define a Nagios service check in one place in the pillar data, and for both the NRPE-daemon-running minion and the Nagios-running minion to emit appropriate configurations for each. The data added to `pillar.example` illustrates how to use this data. As the author, it's hard to judge how straightforward this is; please let me know if actual documentation is necessary.
There is one breaking change: I changed the name of the `nagios.nrpe.checks` dict (used to embed `command[...]=...` lines directly into `nrpe.cfg`) to be `nagios.nrpe.nrpe_commands`. This is to reduce confusion about where checks (in the broader sense) are defined vs simpler command specifications. …

Dynamic commands, services, and NRPE associations

---

pillar.example

The way in which both illegal_object_name_chars and
illegal_macro_output_chars were defined in the example pillar caused
rendering errors in Yaml as `:` was interpreted as being part of a
mapping definition. This patch quotes special characters in there
explicitly and thereby happifies the parser.
See #26 for further details.

Quote special characters in pillar.example

---

nagios/map.jinja

This commit fixes #20 by declaring 'cfg_dir' which was forgotten in
5268b10 (merged in #16).

Add missing 'cfg_dir' setting in map.jinja

---

nagios/map.jinja

Hello,
just observed, that Debian/Ubuntu uses nagios.cfg and cgi.cfg config filenames. This should fix defaults from nagios.conf to nagios.cfg and cgi.conf to cgi.cfg respectively.

fix Debian/Ubuntu default config file name

---

nagios/nrpe/files/nrpe.cfg.jinja

This used to break if nrpe_commands wasn't defined in the pillar. See #27 for details.

Perform safe nrpe_commands pillar lookup

---

nagios/map.jinja

default of 'plugin_dir' does not work with debian, unless it is defined in the 'Debian' section
'nrpe.cfg' does not compile if 'nrpe_command' is not defined in yaml-file. But it should compile even if you have no nrpe_command defined.
It would also solve problems mentioned in issue  #28

disable need for nrpe_commands, avoid definition of plugin_dir in yaml

---

nagios/nrpe/files/nrpe.cfg.jinja

this is the default behavior on Debian based systems. The map.jinja has 'cfg_dir' set on Debian, other systems default to 'false' and do not include the include_dir directive.

adds support for a nrpe include_dir

---

nagios/nrpe/dynamic.sls

This fixes a bug with the file mode which was 0755 and not quoted. See warning on this page for details.
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html

fix file mode in nrpe.dynamic

---

nagios/nrpe/files/nrpe.cfg.jinja
pillar.example

This is to allow the pid_file location to be obtained from pillar.

Make nrpe pid file location configurable.

---

nagios/nrpe/files/nrpe.cfg.jinja

This change is to modify the behavior of the generation of the client nrpe.cfg file. This is to make the server_address declaration optional rather than mandatory.

Modified nrpe server_address injection behavior.

---

nagios/server/files/resource.cfg
pillar.example

This allows one to populate the pillar with username/password data that will be injected in to the resource config file - making it available for nagios checks. Each of the references are an optional pillar item and I also included the event handler reference as well.

Pull resource.cfg data from pillar

---

nagios/map.jinja

On Redhat, nrpe runs as user nrpe, not nagios.
Directory /var/run/nrpe is automatically created and owned by nrpe.
Should fix #51

Fix pid_file path on redhat.

---

nagios/nrpe/server.sls

Since default nrpe config path is hadcoded, there is no way to handle that file. Also notice that root group in freebsd doesn't exists.

Handle FreeBSD default nrpe config.

---

nagios/map.jinja

Nrpe 2 was deprecated see https://www.freshports.org/net-mgmt/nrpe-ssl/

Update nrpe server and service for FreeBSD

---

nagios/map.jinja
nagios/nrpe/dynamic.sls
nagios/nrpe/server.sls

Add the conf.d behaviour to redhat systems to use the better yaml syntax of defining nagios checks

Add compability to use nrpe on RedHat os_family with nrpe.d style

---

nagios/server/files/nagios.cfg
pillar.example

With this PR it will be possible to use the ocsp_command and configure it via pillars. If pillar is not set, this optin will be only a comment in the config file.

add ocsp_command in nagios.cfg

---

nagios/map.jinja
nagios/nrpe/dynamic.sls
pillar.example

Explictly set mode for those files, as they would not work if not readable by
nrpe.

nrpe/dynamic: mode for cmd files (nrpe.d/*)

---

nagios/nrpe/server.sls

This can be important if the install part fails. 
On RHEL the package will set some selinux context on `/etc/nagios/nrpe.conf` so if the file has been deployed before the package the service won't be able to read the file. See : https://superuser.com/questions/1088817/nrpe-centos-7-could-not-open-config-directory

[nagios/nrpe/server] add require between config file and pkg

---

nagios/osfamilymap.yaml

Use /var/spool/nagios instead of (ab)using the logdir /var/log/nagios.

Update paths to actually match Red Hat installs

---

nagios/osfamilymap.yaml

nagios/nrpe/dynamic.sls requires the variable to be set when the
os_family is either Debian or RedHat, not just Debian.
Signed-off-by: Matthew Thode <mthode@mthode.org>

set cmd_mode on RedHat
